[I 14:38:16.967 NotebookApp] [nb_conda_kernels] enabled, 9 kernels found
[I 14:38:17.418 NotebookApp] Authentication of /metrics is OFF, since other authentication is disabled.
[W 14:38:21.791 NotebookApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[W 2023-02-08 14:38:27.532 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2023-02-08 14:38:27.538 LabApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-08 14:38:27.538 LabApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-08 14:38:27.538 LabApp] 'token' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-08 14:38:27.539 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-08 14:38:27.539 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-08 14:38:27.539 LabApp] 'password' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
[W 2023-02-08 14:38:27.540 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[W 2023-02-08 14:38:27.548 LabApp] Config option `kernel_spec_manager_class` not recognized by `LabApp`.
[I 2023-02-08 14:38:27.549 LabApp] JupyterLab extension loaded from /om/user/leokoz8/envs/boa_rnn/lib/python3.8/site-packages/jupyterlab
[I 2023-02-08 14:38:27.549 LabApp] JupyterLab application directory is /om/user/leokoz8/envs/boa_rnn/share/jupyter/lab
[I 14:38:27.556 NotebookApp] Serving notebooks from local directory: /net/vast-storage.ib.cluster/scratch/vast/fiete/leokoz8/code/boa_rnn
[I 14:38:27.556 NotebookApp] Jupyter Notebook 6.3.0 is running at:
[I 14:38:27.556 NotebookApp] http://node053:9000/
[I 14:38:27.556 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 14:39:10.705 NotebookApp] 302 GET / (172.16.24.254) 1.610000ms
/om/user/leokoz8/envs/boa_rnn/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
Exception in callback <TaskWakeupMethWrapper object at 0x2b95cf82ddc0>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2b95cf82ddc0>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/boa_rnn/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-7' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/boa_rnn/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /api/co...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/boa_rnn/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /om/user/leokoz8/envs/boa_rnn/lib/python3.8/site-packages/jupyter_client/manager.py:71>> is being executed.
Exception in callback <TaskWakeupMethWrapper object at 0x2b95cf82d4c0>(<Future finis...late\r\n\r\n'>)
handle: <Handle <TaskWakeupMethWrapper object at 0x2b95cf82d4c0>(<Future finis...late\r\n\r\n'>)>
Traceback (most recent call last):
  File "/om/user/leokoz8/envs/boa_rnn/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
RuntimeError: Cannot enter into task <Task pending name='Task-8' coro=<HTTP1ServerConnection._server_request_loop() running at /om/user/leokoz8/envs/boa_rnn/lib/python3.8/site-packages/tornado/http1connection.py:825> wait_for=<Future finished result=b'GET /kernel...flate\r\n\r\n'> cb=[IOLoop.add_future.<locals>.<lambda>() at /om/user/leokoz8/envs/boa_rnn/lib/python3.8/site-packages/tornado/ioloop.py:687]> while another task <Task pending name='Task-2' coro=<KernelManager._async_start_kernel() running at /om/user/leokoz8/envs/boa_rnn/lib/python3.8/site-packages/jupyter_client/manager.py:71>> is being executed.
[I 14:41:21.008 NotebookApp] Kernel started: 4dde8993-9e06-4891-abfc-a9db01224ad8, name: python3
/om/user/leokoz8/envs/boa_rnn/lib/python3.8/json/encoder.py:257: UserWarning: date_default is deprecated since jupyter_client 7.0.0. Use jupyter_client.jsonutil.json_default.
  return _iterencode(o, 0)
[I 14:43:20.763 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[I 14:45:20.736 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[I 14:51:21.286 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[I 15:05:21.294 NotebookApp] Saving file at /notebooks/test_nb.ipynb
[I 15:07:42.901 NotebookApp] Starting buffering for 4dde8993-9e06-4891-abfc-a9db01224ad8:9c21ad10332f48f082dec9c48e0d88a5
[I 16:29:04.393 NotebookApp] 302 GET / (172.16.24.254) 63.520000ms
